import type ClaudianPlugin from '../../../main';
import type {
  ChatRuntime,
  ChatRuntimeQueryOptions,
  ChatRuntimeEnsureReadyOptions,
  ChatRuntimeConversationState,
  PreparedChatTurn,
  ChatTurnRequest,
  StreamChunk,
  SlashCommand,
  ChatRewindResult,
  ApprovalCallback,
  AskUserQuestionCallback,
  ExitPlanModeCallback,
  SubagentRuntimeState,
  AutoTurnResult,
  ChatTurnMetadata,
  SessionUpdateResult,
} from '../../../core/runtime/ChatRuntime';
import type { ChatMessage, Conversation, ProviderCapabilities, ToolCallInfo } from '../../../core/types';
import type { ProviderCliResolver } from '../../../core/providers/types';
import { spawn } from 'child_process';
import * as os from 'os';
import { QWEN_PROVIDER_CAPABILITIES } from '../capabilities';

interface QwenChatRuntimeDependencies {
  cliResolver: ProviderCliResolver;
}

export class QwenChatRuntime implements ChatRuntime {
  readonly providerId = 'qwen';
  private plugin: ClaudianPlugin;
  private dependencies: QwenChatRuntimeDependencies;
  private abortController: AbortController | null = null;
  private childProcess: ReturnType<typeof spawn> | null = null;
  private readyStateListeners: ((ready: boolean) => void)[] = [];
  private sessionId: string | null = null;
  private sessionInvalidated = false;

  constructor(plugin: ClaudianPlugin, dependencies: QwenChatRuntimeDependencies) {
    this.plugin = plugin;
    this.dependencies = dependencies;
  }

  getCapabilities(): Readonly<ProviderCapabilities> {
    return QWEN_PROVIDER_CAPABILITIES;
  }

  prepareTurn(request: ChatTurnRequest & { text?: string }): PreparedChatTurn {
    const userMessage = request.text || request.userMessage || '';
    return {
      request: request,
      userMessage: userMessage,
      userMessageId: request.userMessageId,
      model: request.model || 'default',
      reasoningEffort: request.reasoningEffort || 'medium',
      attachments: request.attachments || [],
      externalContext: request.externalContext || [],
      requiresOcr: request.requiresOcr || false,
      isAutoGenerated: request.isAutoGenerated || false,
      // 下面是必须的字段
      persistedContent: '',
      prompt: '',
      isCompact: false,
      mcpMentions: new Set(),
    };
  }

  onReadyStateChange(listener: (ready: boolean) => void): () => void {
    this.readyStateListeners.push(listener);
    return () => {
      this.readyStateListeners = this.readyStateListeners.filter(l => l !== listener);
    };
  }

  setResumeCheckpoint(checkpointId: string | undefined): void {
    // 空实现
  }

  syncConversationState(
    conversation: ChatRuntimeConversationState | null,
    externalContextPaths?: string[],
  ): void {
    // 空实现
  }

  async reloadMcpServers(): Promise<void> {
    // 空实现
  }

  async ensureReady(options?: ChatRuntimeEnsureReadyOptions): Promise<boolean> {
    return true;
  }

  async *query(
    turn: PreparedChatTurn,
    conversationHistory?: ChatMessage[],
    queryOptions?: ChatRuntimeQueryOptions,
  ): AsyncGenerator<StreamChunk> {
    this.abortController = new AbortController();

    try {
      const userMessage = turn.request?.text || turn.request?.userMessage || turn.userMessage || '';
      console.log('[Qwen] 开始执行对话请求，用户消息:', userMessage);

      const qwenSettings = this.plugin.settings.providerConfigs.qwen || {};
      const cliPath = this.dependencies.cliResolver.resolveFromSettings(qwenSettings);

      console.log('[Qwen] 解析到的CLI路径:', cliPath);

      if (!cliPath) {
        const errMsg = '未找到Qwen Code CLI，请在设置中配置路径';
        console.error('[Qwen]', errMsg);
        yield { type: 'error', message: errMsg };
        return;
      }
      if (!userMessage) {
        const errMsg = '用户消息不能为空';
        console.error('[Qwen]', errMsg);
        yield { type: 'error', message: errMsg };
        return;
      }

      // 准备Qwen CLI正确参数，优先用用户配置的node路径，默认用/opt/homebrew/bin/node
      const nodePath = qwenSettings.nodePath || '/opt/homebrew/bin/node';
      const args = [cliPath];
      if (this.sessionId) {
        args.push('--session-id', this.sessionId);
      }
      // 把用户消息作为位置参数传递
      args.push(userMessage);

      console.log('[Qwen] 启动命令:', nodePath, args.join(' '));

      const cwd = this.plugin.app.vault.adapter.basePath;
      const homeDir = os.homedir();

      this.childProcess = spawn(nodePath, args, {
        cwd,
        env: {
          HOME: homeDir,
          PATH: `/opt/homebrew/bin:/usr/local/bin:${homeDir}/.local/bin:${homeDir}/.qwen/bin:${process.env.PATH || ''}`,
          ...process.env,
          ...(qwenSettings.customEnvironment || {}),
        },
        signal: this.abortController.signal,
      });

      let fullResponse = '';
      let error: string | null = null;

      const stdoutHandler = (data: Buffer) => {
        const chunk = data.toString();
        console.log('[Qwen] 输出:', chunk);
        fullResponse += chunk;
      };

      const stderrHandler = (data: Buffer) => {
        const errChunk = data.toString();
        console.error('[Qwen] 错误输出:', errChunk);
      };

      this.childProcess.stdout?.on('data', stdoutHandler);
      this.childProcess.stderr?.on('data', stderrHandler);

      const exitCode = await new Promise<number | null>((resolve) => {
        this.childProcess?.on('close', (code) => resolve(code));
        this.childProcess?.on('error', (err) => {
          error = `Qwen CLI 启动错误: ${err.message}`;
          resolve(1);
        });
      });

      this.childProcess.stdout?.off('data', stdoutHandler);
      this.childProcess.stderr?.off('data', stderrHandler);

      if (exitCode !== 0 && exitCode !== null) {
        const errMsg = error || `Qwen CLI 执行失败，退出码: ${exitCode}`;
        console.error('[Qwen]', errMsg);
        yield { type: 'error', message: errMsg };
        return;
      }

      console.log('[Qwen] 执行完成，完整响应:', fullResponse);
      yield { type: 'text', content: fullResponse };
      yield { type: 'complete', content: fullResponse };
    } catch (e) {
      const errMsg = `执行失败: ${String(e)}`;
      console.error('[Qwen] 运行时异常:', e);
      yield { type: 'error', message: errMsg };
    }
  }

  isReady(): boolean {
    return true;
  }

  async getSupportedCommands(): Promise<SlashCommand[]> {
    return [];
  }

  resetSession(): void {
    this.sessionId = null;
    this.sessionInvalidated = true;
  }

  getSessionId(): string | null {
    return this.sessionId;
  }

  consumeSessionInvalidation(): boolean {
    const invalidated = this.sessionInvalidated;
    this.sessionInvalidated = false;
    return invalidated;
  }

  rewind(userMessageId: string, assistantMessageId: string): Promise<ChatRewindResult> {
    return Promise.resolve({ success: false });
  }

  setApprovalCallback(callback: ApprovalCallback | null): void {
    // 空实现
  }

  setApprovalDismisser(dismisser: (() => void) | null): void {
    // 空实现
  }

  setAskUserQuestionCallback(callback: AskUserQuestionCallback | null): void {
    // 空实现
  }

  setExitPlanModeCallback(callback: ExitPlanModeCallback | null): void {
    // 空实现
  }

  setPermissionModeSyncCallback(callback: ((sdkMode: string) => void) | null): void {
    // 空实现
  }

  setSubagentHookProvider(getState: () => SubagentRuntimeState): void {
    // 空实现
  }

  setAutoTurnCallback(callback: ((result: AutoTurnResult) => void) | null): void {
    // 空实现
  }

  consumeTurnMetadata(): ChatTurnMetadata {
    return {};
  }

  buildSessionUpdates(params: {
    conversation: Conversation | null;
    sessionInvalidated: boolean;
  }): SessionUpdateResult {
    return {
      sessionId: this.sessionId,
      updates: [],
    };
  }

  resolveSessionIdForFork(conversation: Conversation | null): string | null {
    return this.sessionId;
  }

  async loadSubagentToolCalls?(agentId: string): Promise<ToolCallInfo[]> {
    return [];
  }

  async loadSubagentFinalResult?(agentId: string): Promise<string | null> {
    return null;
  }

  async executeTurn(
    conversation: Conversation,
    turn: { userMessage: string; userMessageId: string; model?: string; reasoningEffort?: string },
    options: {
      onText: (text: string) => void;
      onComplete: (fullResponse: string) => void;
      onError: (error: string) => void;
    },
  ): Promise<void> {
    // 兼容旧版调用逻辑
    this.abortController = new AbortController();

    try {
      const userMessage = turn.text || turn.userMessage || '';
      console.log('[Qwen] 执行对话请求:', userMessage);

      const qwenSettings = this.plugin.settings.providerConfigs.qwen || {};
      const cliPath = this.dependencies.cliResolver.resolveFromSettings(qwenSettings);

      if (!cliPath) {
        const errMsg = '未找到Qwen Code CLI，请在设置中配置路径';
        console.error('[Qwen]', errMsg);
        options.onError(errMsg);
        return;
      }
      if (!userMessage) {
        const errMsg = '用户消息不能为空';
        console.error('[Qwen]', errMsg);
        options.onError(errMsg);
        return;
      }

      // 准备Qwen CLI正确参数，优先用用户配置的node路径，默认用/opt/homebrew/bin/node
      const nodePath = qwenSettings.nodePath || '/opt/homebrew/bin/node';
      const args = [cliPath];
      if (conversation.id) {
        args.push('--session-id', conversation.id);
      }
      // 把用户消息作为位置参数传递
      args.push(userMessage);

      console.log('[Qwen] 命令:', nodePath, args.join(' '));

      const cwd = this.plugin.app.vault.adapter.basePath;
      const homeDir = os.homedir();

      this.childProcess = spawn(nodePath, args, {
        cwd,
        env: {
          HOME: homeDir,
          PATH: `/opt/homebrew/bin:/usr/local/bin:${homeDir}/.local/bin:${homeDir}/.qwen/bin:${process.env.PATH || ''}`,
          ...process.env,
          ...(qwenSettings.customEnvironment || {}),
        },
        signal: this.abortController.signal,
      });

      let fullResponse = '';
      let error: string | null = null;

      this.childProcess.stdout?.on('data', (data) => {
        const chunk = data.toString();
        console.log('[Qwen] 输出:', chunk);
        fullResponse += chunk;
        options.onText(chunk);
      });

      this.childProcess.stderr?.on('data', (data) => {
        const errChunk = data.toString();
        console.error('[Qwen] 错误输出:', errChunk);
      });

      this.childProcess.on('close', (code) => {
        if (code === 0 || code === null) {
          console.log('[Qwen] 完成:', fullResponse);
          options.onComplete(fullResponse);
        } else {
          const errMsg = error || `Qwen CLI 执行失败，退出码: ${code}`;
          console.error('[Qwen]', errMsg);
          options.onError(errMsg);
        }
      });

      this.childProcess.on('error', (err) => {
        const errMsg = `Qwen CLI 启动错误: ${err.message}`;
        console.error('[Qwen]', errMsg);
        options.onError(errMsg);
      });
    } catch (e) {
      const errMsg = `执行失败: ${String(e)}`;
      console.error('[Qwen] 异常:', e);
      options.onError(errMsg);
    }
  }

  cancel(): void {
    this.abortController?.abort();
    if (this.childProcess && !this.childProcess.killed) {
      this.childProcess.kill('SIGTERM');
    }
  }

  async cleanup(): Promise<void> {
    this.cancel();
  }
}
